/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'john' at '23/10/14 8:30 PM' with Gradle 2.1
 *
 * @author john, @date 23/10/14 8:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
